# Generated by Django 3.0.8 on 2020-09-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_auto_20200908_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProductRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('product_name', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('request_seen', models.BooleanField(default=False)),
            ],
        ),
    ]
